### ISSUE TITLE
Video-link-checker generating an empty text file

### ISSUE THREAD

**Issue by gabriellluz** [NapoleonWils0n/kodi-playercorefactory#51] opened 2016-12-10 19:01 UTC
Hi there.

Thank you for your wonderful tool. I have an IPTV list and most streams actually work. But when I use video-link-checker all I get is an empty working-links.txt file with not streams at all. I've tried other lists too. I use Windows 10. I've given all permissions to working-links.txt I've tried running even as admin and it doesn't work.

**Comment by NapoleonWils0n** [comment] 2016-12-10 19:32
hi mate

so when you run the video-link-checker script to check a file with urls it creates the working-links.txt file but its empty

what file extension does the file your are checking have
.txt or .m3u

does the file you are checking have a .m3u8 file extension ?

it could be that the script isnt catching the urls with the regular expression
you mentioned you have tried some other lists as well

have you tried checking something simply like a link to an mp4

did you install ffprobe ?

i havent updated that script for a while, will put it in my todo list and improve the regular expression to catch url

could you post a link you are trying to check and ill have a look at my end

just set up windows 10 in a virtual machine and im going to clone it onto an external usb drive i can boot up from
ill have a look on the windows side later as well

ps
Should have a Windows GUI installer soon to install all the programs and scripts,
will work on windows xp to windows 10, 32 and 64 bit

should make the windows install easier

**Comment by gabriellluz** [comment] 2016-12-10 19:54
The file I'm checking has a m3u extension. I've always used it on Kodi. It works fine. FFprobe works from the command line. I've tested a stream right now and FFprobe just showed me all details about my stream so it works fine.

**Comment by gabriellluz** [comment] 2016-12-10 19:56
Part of my list:
#EXTINF:-1 tvg-logo="https://lut.im/xM59bKJyWh/wtncdEwp4NSPNkDB.png" group-title="TV Aberta",[COLOR blue][I][B]REDETV RONDÔNIA[/B][/I][/COLOR]
http://173.236.10.10:1935/tvonline/tvonline/playlist.m3u8

#EXTINF:-1 tvg-logo="https://lut.im/wY8Du7LA6R/9dBVtNqL8vDSLeDX.jpeg" group-title="TV Aberta",[COLOR blue][I][B]Cultura BA[/B][/I][/COLOR]
http://cdn-br-002938543.comets.com.br/tvbaiana/aovivo/chunklist_w1472016693.m3u8

#EXTINF:-1 tvg-logo="https://lut.im/pCrpclwOJC/5LCMQBFHyHLHKJ33.png" group-title="TV Aberta",[COLOR blue][I][B]Cultura PB[/B][/I][/COLOR]
http://cdn-br-002938543.comets.com.br/tvnovanordeste/aovivo/playlist.m3u8

#EXTINF:-1 tvg-logo="https://lut.im/e72onG9WKf/4QzLhjr6jmTkY7yw.png" group-title="TV Aberta",[COLOR blue][I][B] TV CULTURA HD - ITARARÉ PB[/B][/I][/COLOR]
http://177.73.84.49/hls/57290d5d9a175/57290d5d9a175.m3u8

#EXTINF:-1 tvg-logo="https://lut.im/PFyHGKW1Zi/6XASjzxXuCMhecVB.png" group-title="TV Aberta",[COLOR blue][I][B]SBT SP INTERIOR[/B][/I][/COLOR]
http://srv6.zoeweb.tv:1935/z343-live/stream/playlist.m3u8

#EXTINF:-1 tvg-logo="https://lut.im/PFyHGKW1Zi/6XASjzxXuCMhecVB.png" group-title="TV Aberta",[COLOR blue][I][B]SBT HD[/B][/I][/COLOR]
http://gbbrlive2.sambatech.com.br/liveevent/sbtabr_8fcdc5f0f8df8d4de56b22a2c6660470/livestream4/playlist.m3u8

I've tried this too.

Your script works but it generates an empty working-links.txt file.

**Comment by NapoleonWils0n** [comment] 2016-12-10 20:32
hi mate

just checked on linux and it worked

open the windows command prompt and the change to the Desktop by running this

```
cd Desktop
```

then run the script

```
video-link-checker
```

it will prompt you for a text file
eg if you have a text file on the Desktop called links.txt, type link.txt

that will run the script and save the working links in a text file called workinglinks.txt

i need to improve the script because it was also checking the jpg and png files

try putting all the m3u8 links in a text file called links then run the script as above and see if that works

**Comment by gabriellluz** [comment] 2016-12-10 20:46
Hi, typing cd Desktop doesn't work. It won't take me anywhere. I've tried going to my desktop folder. Still no go. Also, I always have to type "bash video-link-checker". Then it prompts me with a question. I type "list.m3u".

**Comment by gabriellluz** [comment] 2016-12-10 20:48
Yes, it checks all jpeg (my tv logos).

**Comment by NapoleonWils0n** [comment] 2016-12-10 20:54
Hi mate

Are you using the Windows command prompt

You should be able to change to the desktop with the windows command prompt by typing

```
cd Desktop
```

* yes you have to runthe script like this on windows

```
bash video-link-checker
```

The problem is you are running the script in your home folder but the text file is on the desktop so it cant find the file

try this to resolve the issue

when it prompts you for the file type this

```
Desktop/list.m3u
```

that will create a working-links.txt file in your home

**Comment by gabriellluz** [comment] 2016-12-10 21:03
Didn't work.

So, let me explain where are the files located:

I've installed cygwin, curl, sed, grep, everything.

I've put your scripts at C:\bash-scripts-windows and I have included C:\bash-scripts-windows as a PATH in Windows variables. So everytime I run video-link-checker I have to type in the command prompt
`C:\`
`cd bash-scripts-windows`
`bash video-link-checker`

then it says:
`enter the path to your text file:`
I type `list.m3u` because the file is in the same folder as C:\bash-scripts-windows

Then it outputs:
`Checking: http://gbbrlive2.sambatech.com.br/liveevent/sbtabr_8fcdc5f0f8df8d4de56b22a2c6660470/livestream4/playlist.m3u8`

End.
No working-links.txt file generated.



My m3u list is located at the same location as C:\bash-scripts-windows If I don't do this, it won't open my list.m3u.

**Comment by gabriellluz** [comment] 2016-12-10 21:09
It generates an empty working-links.txt file. Forgot to mention.

**Comment by NapoleonWils0n** [comment] 2016-12-10 21:21
Hi Mate
You have the scripts in the wrong place

You need to create folder called git in your home folder,
and then download the scripts with git into the git folder in your home

https://github.com/NapoleonWils0n/kodi-playercorefactory/tree/master/windows#git-install

Did you download the scripts with git or just download them as a zip file ?

* Your windows system path should have this in it

```
C:%HOMEPATH%\git\kodi-playercorefactory\bash-scripts-windows;
```

This bit is wrong 

"I've put your scripts at C:\bash-scripts-windows and I have included C:\bash-scripts-windows as a PATH in Windows variables. So everytime I run video-link-checker I have to type in the command prompt
C:\
cd bash-scripts-window
bash video-link-checker"

You dont need to cd into c:\bash-scripts-windows, thats why its not working

You need to install download the whole git repository into a a folder called git in your home folder

so it should look like this

```
your-home/git/kodi-playercorefactory
```

* So the windows scripts will be installed to

```
your-home/git/kodi-playercorefactory/bash-scripts-windows
```

* You need to add this to your windows system path

```
C:%HOMEPATH%\git\kodi-playercorefactory\bash-scripts-windows;
```

When you run the scripts you dont cd into the folder where the scripts are installed,
you need to edit your windows system path as above

Then you can run the scripts from anywhere

Then you can do the following

* change to the desktop 

```
cd Desktop
```

* run the script

```
bash video-link-checker
```

* it will prompt you for a file, make sure the file is on the desktop and type the file name

```
list.m3u
```

**Comment by gabriellluz** [comment] 2016-12-11 11:34
OK. :) Will try that. :D

**Comment by NapoleonWils0n** [comment] 2016-12-11 16:04
Hi Mate

I should have a GUI windows installer soon which will install everything for you

Hopefully within the next week

**Closed as completed** 2016-12-15 02:10 UTC

**Comment by gabriellluz** [comment] 2016-12-15 14:13
Ok. I just lost my Windows installation. I'm gonna have to reinstall it again ¬¬.
