### ISSUE TITLE
window cant find bash

### ISSUE THREAD

**Issue by steve55792** [NapoleonWils0n/kodi-playercorefactory#14] opened 2016-06-09 02:44 UTC
Hi, When I hit the record button to record in kodi, windows says it cant find the bash. What did i do wrong here?

Thanks
Steve

**Comment by NapoleonWils0n** [comment] 2016-06-09 15:18
Hi steve55792 , its not you mate its a bug going back to Windows 7 where Windows forgets what in the system path

You just need to edit your Windows system path and click ok ( and maybe reboot )
then Windows will remember whats in the system path and the scripts should work

You can also try reinstalling cygwin, by double click the cygwin installer and clicking next, next ok

Make sure to follow the read me page below and watch the windows set up video if you get stuck

Let me know if that resolves the issue

**Comment by steve55792** [comment] 2016-06-09 23:36
I have a Nivida Shield Tv , is it the same procedure for the Android  because basically I use this mainly for watching Tv.
                                                                                                                                                Thanks                                                                                                                                       Steve

**Comment by steve55792** [comment] 2016-06-09 23:53
I watched the video and followed directions and it still says windows cant find bash script. The only thing i can do is save the url and play the url thru vlc.
 thanks
 steve

**Comment by NapoleonWils0n** [comment] 2016-06-10 00:24
Hi steve55792
I havent been able to get the scripts to work on Android,
because its difficult to install ffmpeg and the command line tools needed on Android
You can install the scripts onto a Rapsberry Pi and plug that into your tv

But the scripts work on Linux, Mac osx and Windows.

The problem is Windows cant find where cygwin has installed bash.
Its a bug i have come across several times and it goes back to windows 7

Have you tried editing your windows system path and reinstalling cygwin and rebooting

Check your windows system path
- open the windows command prompt ( the terminal )
- type the code below into the terminal and press return

```
echo $PATH
```

This will echo the windows system path to the terminal window
Check that it matches the system path on the windows read me page

https://github.com/NapoleonWils0n/kodi-playercorefactory/tree/master/windows#add-rtmpdump-to-your-windows-system-path

You can also check the scripts on the command line
- save a url from kodi by pressing y on the keyboard and selecting save url
- open the windows command prompt ( the terminal )
- change directory to the Desktop by typing in the code below in the terminal and pressing return

```
cd Desktop
```

Next try and run one of the scripts on the command line 
Try and run the rip-play-mpv script and use the text file with the url you saved from kodi as an argument to the script.

When you run the scripts on the command line you need to add the word bash before the name of the script. eg when we run rip-play-mpv we type bash rip-play-mpv in the terminal

Type the code below into the terminal and press return, replacing videourl.txt with the name of the text file with the url you saved from Kodi

```
bash rip-play-mpv videourl.txt
```

Also make sure you are running the latest version of the scripts by doing a git pull,
and make sure to copy the newest playercorefactory.xml to your kodi userdata directory

Let me know how you get on

**Comment by steve55792** [comment] 2016-06-10 02:14
echo $PATH Says : $Path. Do you use teamviewer? I tried thebash rip-play-mpv videourl.txt and that says bash is not recognized as a command.
steve

**Comment by steve55792** [comment] 2016-06-10 02:28
The only thing working is the save url text. I can manually record in vlc but is there away to batch record in kodi?

**Comment by NapoleonWils0n** [comment] 2016-06-10 13:54
Hi steve55792 

Sorry your having trouble getting set up
Windows is a right pain in the arse

Running echo $PATH should display your system path in the windows terminal
The command should look like this

```
echo $PATH
```

The issue might be where you have cygwin installed

Cygwin can either install to  C:\cygwin\bin or C:\cygwin64\bin
Have a look at your C drive and see where cygwin is installed

Then check your windows system path and see if it matches
you may need to change the cygwin location in your windows system path

from this

```
;C:\cygwin\bin;
```

to this

```
;C:\cygwin64\bin;
```

https://github.com/NapoleonWils0n/kodi-playercorefactory/tree/master/windows#add-rtmpdump-to-your-windows-system-path

If you google for "windows cannot find bash" you will see this is a very old windows bug going back several years

you can also google for "windows forgets system path" and you will the bug going back to Windows 7

Its a problem with the windows system path and where cygwin is installed

Make sure you dont have any typos in your windows system path or anywhere else, i just spent 4 days helping another Windows user and it turned out to be a typo error they had made

Can only suggest you go through all the install steps, slowly bit by bit and check you dont have any typos or errors. 
And check where cygwin is installed on your C drive and cross reference with whats in your windows system path

The problem is Windows and not you or the scripts

To install and set up all the scripts, ffmpeg and Kodi takes less than 5 minutes on Linux

I have a script called rip-record-batch for batch recording, which you will see in the bash-scripts-windows directory

https://github.com/NapoleonWils0n/kodi-playercorefactory/blob/master/bash-scripts-windows/rip-record-batch

I dont use Teamviewer, i only use open source software
I wouldnt use Teamviewer its been hacked 

http://arstechnica.com/security/2016/06/teamviewer-says-theres-no-evidence-of-2fa-bypass-in-mass-account-hack/

**Comment by steve55792** [comment] 2016-06-10 17:54
How hard would it to be to use or put kodi and your script on ubuntu. I know a little about ubuntu so I think ill give it a shot. I dont know wht went wrong in windows setup, Do you have a youtube video for using it with ubuntu?

**Comment by NapoleonWils0n** [comment] 2016-06-10 18:06
Hi steve55792
It should take you about 5 minutes to set everything up on Ubuntu
I havent made a video for linux because it really does take a couple of minutes

heres the linux set up page

https://github.com/NapoleonWils0n/kodi-playercorefactory#linux-set-up

1 - install the command line tools

```
sudo apt install -y git ffmpeg fdk-aac rtmpdump vlc mpv youtube-dl aria2c
```

2 - create a git folder in your home directory

```
mkdir -p ~/git
```

3 - change directory into the git directory you just created

```
cd ~/git
```

4 - clone the kodi-playercorefactory git repo

```
git clone https://github.com/NapoleonWils0n/kodi-playercorefactory.git
```

5 - copy the playercorefactory.xml file to your kodi userdata folder

```
cp  ~/git/kodi-playercorefactory/linux/combined/playercorefactory.xml ~/.kodi/userdata/playercorefactory.xml 
```

6 - bash scripts set up

add the $HOME/git/kodi-playercorefactory/bash-scripts directory to your bash path

edit your .bashrc in your home directory im using vim to edit the file but you can use any text editor

```
nano ~/.bashrc
```

add the code below to your ~/.bashrc to add the $HOME/git/kodi-playercorefactory/bash-scripts directory to your bash path

the default file path is your home-directory/git/kodi-playercorefactory/bash-scripts if you have downloaded the git repo to a different path then change the code below accordingly

set PATH so it includes the kodi playercorefactory scripts

```
if [ -d "$HOME/git/kodi-playercorefactory/bash-scripts" ] ; then
        PATH="$HOME/git/kodi-playercorefactory/bash-scripts:$PATH"
fi
```

7 - source your ~/.bashrc to pick up the scripts

```
. ~/.bashrc
```

Thats it
Should take you about 5 minutes to set everything up

**Comment by NapoleonWils0n** [comment] 2016-06-10 18:14
Hi steve55792
To install Kodi on ubuntu 

```
sudo apt install -y kodi
```

If you get stuck leave a comment and ill point you in the right direction

**Comment by NapoleonWils0n** [comment] 2016-06-11 13:54
Hi steve55792

I tried running ubuntu in a virtual machine to record the set up
But ubuntu has so many Desktop animations even if you turn them off thats its unusable in a virtual machine and just crashes my laptop

I tried several times and ubuntu would just lock up and i couldnt even move the cursor
The unity desktop is totally unusable in a VM

Just follow the steps above or the main read me page with the ubuntu instructions and you should be able to get set up in a couple of minutes

**Comment by steve55792** [comment] 2016-06-11 16:11
i tried to install the script but ubuntu says its unable to locate packages fdk-acc and aria2c. I just copy and paste to ubuntu terminal. is there a place to download them?

**Comment by NapoleonWils0n** [comment] 2016-06-11 16:42
Hi steve55792 
sometime the package names differ on various linux distros, 
my bad sorry for the confusion, i will update the ubuntu instructions on the git repo 

aria2c is named aria2 on ubuntu 
and libfdk-aac is named libfdk-aac-dev on ubuntu

you can install aria2 with this command 

```
sudo apt install aria2
```

you can install libfdk-aac-dev with this command 

```
sudo apt install libfdk-aac-dev
```

so to install all the tools run the following command

```
sudo apt install -y git ffmpeg fdk-aac-dev rtmpdump vlc mpv youtube-dl aria2
```

let me know if that works for you mate
and good on you for giving linux a shot

let me know if you need any help and ill be on the case

i have updated the ubuntu instructions on the main page,
thanks for catching my error

https://github.com/NapoleonWils0n/kodi-playercorefactory

**Comment by NapoleonWils0n** [comment] 2016-06-11 16:56
Hi Steve

Here where i keep all my code and linux and mac osx tips and tricks, 
its my Brain dump if i know the answer it will be in my cerberus git repo

https://github.com/NapoleonWils0n/cerberus

You can clone my code, tips and tricks git repo by running the commands below

1 - change directory into the git folder in your home

```
cd ~/git
```

2 - then clone the cerberus git repo with this command 

```
git clone https://github.com/NapoleonWils0n/cerberus.git
```

Lots of Linux tips and tricks to get you started

**Comment by steve55792** [comment] 2016-06-12 01:01
So far so good over here, everything is working. Thank you for your help .     
                                                                                        steve

```
  From: NapoleonWils0n <notifications@github.com>
```

 To: NapoleonWils0n/kodi-playercorefactory kodi-playercorefactory@noreply.github.com 
Cc: steve55792 steve55792@yahoo.com; State change state_change@noreply.github.com
 Sent: Saturday, June 11, 2016 11:56 AM
 Subject: Re: [NapoleonWils0n/kodi-playercorefactory] window cant find bash (#14)

Hi SteveHere where i keep all my code and linux and mac osx tips and tricks, 
its my Brain dump if i know the answer it will be in my cerberus git repohttps://github.com/NapoleonWils0n/cerberusYou can clone my code, tips and tricks git repo by running the commands below1 - change directory into the git folder in your homecd ~/git
2 - then clone the cerberus git repo with this command git clone https://github.com/NapoleonWils0n/cerberus.git
Lots of Linux tips and tricks to get you started—

**Comment by NapoleonWils0n** [comment] 2016-06-12 01:37
Hi steve55792 
Glad you managed to get everything working and didnt give up

ill close this issue

**Closed as completed by NapoleonWils0n** 2016-06-12 01:37 UTC

**Comment by steve55792** [comment] 2016-06-14 11:35
how do you add  rip-batch record to ubuntu?

**Comment by steve55792** [comment] 2016-06-14 11:48
I see it is in the bash script windows but i dont see it in the part where you select to save url or record.

**Comment by steve55792** [comment] 2016-06-14 12:25
I see it is in the bash script windows but i dont see it in the part where you select to save url or record.
