### ISSUE TITLE
Bash: No such file of directory

### ISSUE THREAD

**Issue by PanzerV1** [NapoleonWils0n/kodi-playercorefactory#6] opened 2016-01-13 10:55 UTC
Hi

I have tried this on Windows 10 and Server 12, but always come up with an error "bash: rip-play:no such file or directory"

I have triple checked the environment variables and all seems fine, I can run Bash in a cmd window and it also works fine

I just can't get it to run your scripts directly from Kodi, I just get the CMD windows briefly flashing 

Any idea what i am doing incorrectly?

Regards

**Comment by NapoleonWils0n** [comment] 2016-01-13 14:20
Hi Mate

Have you followed all the steps on the windows read me page
https://github.com/NapoleonWils0n/kodi-playercorefactory/tree/master/windows

Things to check 

1 - ffmpeg is installed to C:\ffmpeg\bin\ffmpeg
2 - cygwin is installed and you have installed sed and grep with cygwin
3 - you have set up your windows system path
4 - git is set up with Checkout as--is, commit Unix-style line endings
5 - you have download the scripts with git into your-home\git\kodi-playercorefactory

Can you see if you can run the scripts from the command line
for example save the url of a video from kodi by pressing y while a video is playing and selecting save url, this will create a text file on your desktop called videourl.txt

open the terminal and change directory to the desktop

```
     cd Desktop
```

then try and run the rip-play script on the videourl.txt file

```
     bash rip-play videourl.txt
```

if that doesnt work try specifying the full path to the script, replace your-home with the path to your home folder

```
  bash C:\your-home\git\kodi-playercorefactory\bash-scripts-windows\rip-play videourl.txt
```

There is a windows bug where sometimes it forgets part of your system path, try opening up your windows system path again and then closing the window. sometimes it makes windows remember where things are installed

try reinstalling cygwin by double clicking the installer to re run it and you should get a package install window, search for grep, sed and cat and make sure you have them installed, if not install them

make sure you download the scripts with git and set unix line endings
check you have added everything to your windows system path, it could just be a typo

I have tested the scripts on Windows 10 and they do work but i haven't tried installing the scripts on a windows server but it should work

**Comment by PanzerV1** [comment] 2016-01-14 11:35
Thanks for the response, I tried the following and everything is working perfectly 

bash C:\your-home\git\kodi-playercorefactory\bash-scripts-windows\rip-play videourl.txt

any idea why your batch script is not being picked up in the CMD window, this is my "Environment Variables"

%PATH%;C:\Python27;%USERPROFILE%\AppData\Local.meteor;C:\cygwin\bin;C:\ffmpeg\bin;C:\Program Files\Git\cmd;C:%HOMEPATH%\git\kodi-playercorefactory\bash-scripts-windows;C:\curl\bin;C:\youtube-dl\bin;C:\windump\bin;C:\notify-send\bin;C:\aria2c\bin;C:\notify-send\bin;C:\aria2c\bin

**Comment by NapoleonWils0n** [comment] 2016-01-14 15:47
Hi Mate
The scripts are installed correctly, but it looks like the windows system path isnt picking up the location of the scripts, its a windows bug going back several years.

You seem to have C:\notify-send in the path twice, try removing one see if that helps

Can you try re adding the variables to the system path and see if windows then remembers where the scripts are installed.

Edit your windows system path and copy and paste it into a text file on the desktop so you have a backup, then remove all the variables you have added for the scripts, cygwin, git ffmpeg, youtube-dl notify send.

Then click save
Then edit the system path again and re add all the script variables, double check for typos and then save the settings again. That may fix the problem

You could also try changing the order of the variables in the system path, eg add path to scripts, then ffmpeg and then all the other variables

If you google for "windows forgets system path"  you see the bug goes back to windows 7 in 2011

Im pretty sure the problem is the windows system path, i had the same issue myself and re editing the system path seemed to fix the problem

**Comment by PanzerV1** [comment] 2016-01-14 15:53
Thanks, I will give it shot tonight

a bit off topic, but can you send a Kodi IPTV stream directly to VLC? 

Regards

**Comment by NapoleonWils0n** [comment] 2016-01-14 16:49
Hi Mate
Not off topic at all

VLC doesnt support custom http headers which are used by a lot of kodi iptv streams, so VLC wont play a lot of video streams from Kodi

However i have created a script called rip-stream that will take a video stream from Kodi re encodes the video and multicast stream it to your router, you can then open that stream with VLC and play it. You can use the script from within Kodi or on the command line.

So you can rebroadcast the stream on your home network and then tune into the stream with all the devices on your network, sort of like creating your own tv network on your lan

It use the h265 codec for streaming but i can always change it to use h264 if you cant get h265 installed or if vlc wont play h265

videos showing multicast streaming

multicast streaming
https://www.youtube.com/watch?v=OYYo9z-1zHM

multicast streaming and set duration for the stream
https://www.youtube.com/watch?v=Yf98wDD10dI

Hope you manage to fix the windows system path, i had the same problem myself

**Comment by PanzerV1** [comment] 2016-01-14 22:16
yes all sorted on Windows, your trick worked the 2nd time :)

Rip-Stream script is working perfectly, just had one problem playing back in VLC, I just needed to add a @ to the UDP string when entering it into VLC

like the following udp://@ipaddress:1234

Thanks for all your help and brilliant scripts

Regards

**Comment by NapoleonWils0n** [comment] 2016-01-14 22:38
Hi Mate

Glad you managed to get everything working
I had the same bug it had me baffled for a while

Ill mark the issue as closed

**Closed as completed by NapoleonWils0n** 2016-01-14 22:38 UTC
