### ISSUE TITLE
cannot create temp file for here document: permission denied

### ISSUE THREAD

**Issue by ghost** [NapoleonWils0n/kodi-playercorefactory#85] opened 2017-07-22 18:32 UTC
![screenshot 2017-07-22 13 53 25](https://user-images.githubusercontent.com/30375754/28493786-9396960c-6eea-11e7-89ad-fc5668829673.png)
need help with this.

**Comment by NapoleonWils0n** [comment] 2017-07-22 21:10
hi mate

i know what that error is

there is a tmp folder inside the rip-record folder
you need to change the permissions on the tmo folder so you have write acces

i didnt actually write the window installer
another user called the terminator wrote the installer

i believe the issue is fixed in the latest version of the installer

try changing the permission on the tmp folder explained above and see if that helps
or try newer version of the installer

if you get stuck best raise an issue on the windows installer github page with the terminator
im not a windows users and the terminator who wrote the installer is a windows certified enginer

so if you get stuck he'll be able to point you in the right direction

**Comment by ghost** [comment] 2017-07-22 22:27
save video url doesnt seem to work either, i get the external player message telling me to click ok to close the current video on kodi, but the external player never opens. i used the latest version of the installer

**Comment by NapoleonWils0n** [comment] 2017-07-23 02:02
hi mate

there is a windows bug going back to windows 7
where windows forgets whats in its system path and so cant find the program

that could be the issue

what you have to do is edit your windows system path and copy all of the system path
and than paste it into notepad ++ and save the file to the desktop as path.txt

then edit the windows system path again and delete everything in it and click ok

then edit the win sys path again and paste the path back in from the path.txt file you saved to the desktop
then click ok

i made a video about fixing the windows system path bug
if you look in the playlist its one of the video with a windows thumbail for the video
called something windows system path fix

you can check if windows can find the script by opening the windows command prompt 
and then typing the code below

```
bash rip-record
```

that should display the script usage message in the windows command prompt

if it does it means you should be good to go as long 
as you gave yourself write permission to the tmp folder in the rip-record folder

this issue is a windows problem going back 5 or 6 years to windows 7 and still hasnt been fixed in windows 10

so the issue of not being able to find the scripts 
so you cant even save the url from kodi only happens on windows and not on other operating systems

the bug happens now again on windows and the only fix is to edit your win system path to fix the issue
or use another operating system like linux, freebsd or mac osx

the set up on linux is very easy and only takes 5 minutes and ubuntu is very easy to install

not being able to save the url sounds like the windows system path bug where it cant find the script

have a look in the playlist and search for windows fix system path and it will show the fix step by step

hope that helps

**Comment by ghost** [comment] 2017-07-23 04:56
you have 12 created playlists, which one is what im looking for? your directions arent exactly clear. i cant tell what exactly im editing and deleting. where am i editing the system path? the only thing i can tell you is the bash rip-record command does work, i get a script message. but i have no idea where to start fixing my problem.

**Comment by NapoleonWils0n** [comment] 2017-07-23 10:09
hi mate

you want video number 74 in the uploads

**Comment by NapoleonWils0n** [comment] 2017-07-24 19:57
hi mate

this is the video showing how to fix the windows command not found error

https://m.youtube.com/watch?v=Xc5QwVR1v9k

**Closed as completed** 2017-07-30 14:08 UTC

**Comment by godfreymakori** [comment] 2020-06-25 03:15
Most probably this is a tmp folder permission issue. For linux: "sudo chmod -R 1777 /tmp" fixes the issue
