### ISSUE TITLE
rip-batch record 

### ISSUE THREAD

**Issue by steve55792** [NapoleonWils0n/kodi-playercorefactory#16] opened 2016-06-14 22:14 UTC
how do you add rip-batch record to ubuntu? I followed your youtube video on kodi batch downloading video 46 and its not working for me. ex: when i type in  rip -r, it says command not found. It says that also when i type in rip-record-batch in the terminal

**Comment by steve55792** [comment] 2016-06-14 22:24
Actually how do you put it in the coulmn where save the url, record for 30, 1 hr, 2 hours. If Im making any sense.

**Comment by NapoleonWils0n** [comment] 2016-06-15 13:24
Hi steve55792, the script is called rip-record-batch
If you have edited you ~/.bashrc and added the path to the scripts they should show up.
Also need to source your ~/.bashrc, source ~/.bashrc

These are the list of bash scripts which should match the scripts you have downloaded

https://github.com/NapoleonWils0n/kodi-playercorefactory/tree/master/bash-scripts

**Comment by steve55792** [comment] 2016-06-15 14:14
I'm sorry but what do you mean if you have edited you ~/.bashrc and added the path to the scripts they should show up, and Also need to source your ~/.bashrc, source ~/.bashrc. sorry to be difficult with this. I can do one at a time but this batch recording is even better
.

**Comment by NapoleonWils0n** [comment] 2016-06-15 14:39
Hi steve55792, no problem mate didnt mean to confuse you

I just meant you had followed this step in the linux set up
https://github.com/NapoleonWils0n/kodi-playercorefactory#step-4---bash-scripts-set-up

If you open the terminal and type rip and then press tab you should see a list of all scripts that start with the word rip in the terminal 

it should look like this

```
rip-play           rip-play-mpv       rip-record         rip-ssh            rip-stream         rip-ytdl           
rip-play-external  rip-play-vlc       rip-record-batch   rip-stats          rip-xiptv          
```

You can check your bash PATH to make sure the scripts are installed properly by typing the command below into the terminal

```
echo $PATH
```

Please post the output of the echo $PATH command in a comment and ill check it for you

Also you cant specify a duration when using the rip-record-batch script, 
batch recording is mean for downloading videos like films and tv show and not recording live tv

You can schedule video recordings to record your favourite tv shows,
im just working on a new way to schedule video recordings and all your recordings will show up in a calendar

let me know if that helps clear things up

**Comment by steve55792** [comment] 2016-06-15 14:59
/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
is the output.

**Comment by steve55792** [comment] 2016-06-15 15:06
is linux and ubuntu  the same or are they different operating system?

**Comment by NapoleonWils0n** [comment] 2016-06-15 15:18
Hi steve55792
Looks like you have missed a step

We need to add the scripts to your bash path

1 - Open the file manager to your home folder

2 - Press control and h, to show hidden files

3 - you should see a file called .bashrc

4 - right click on .bashrc and select open with gedit

5 - paste the code below at the bottom of the .bashrc file

```
if [ -d "$HOME/git/kodi-playercorefactory/bash-scripts" ] ; then
        PATH="$HOME/git/kodi-playercorefactory/bash-scripts:$PATH"
fi
```

6 - Save the .bashrc file with gedit, and then close the file

7 - Select the file manage and Press control and h, to hide hidden files

8 - Open the terminal and paste in the code below and press return

```
source ~/.bashrc
```

9 - Now type rip in the terminal and press tab and you should see a list of all the scripts that start with the word rip

Let me know if that helps

**Comment by NapoleonWils0n** [comment] 2016-06-15 15:23
HI steve55792, ubuntu is linux

you have different linux distibutions, like ubuntu, linux mint, debian
but they are all linux

**Comment by NapoleonWils0n** [comment] 2016-06-15 15:25
Hi steve55792,
After you have added the scripts to your bash PATH, run echo $PATH again and then post the output here

open the teminal and type

```
echo $PATH
```

**Comment by steve55792** [comment] 2016-06-15 19:16
bash: /home/steve/.bashrc: line 3: syntax error near unexpected token `('
bash: /home/steve/.bashrc: line 3:`fi# ~/.bashrc: executed by bash(1) for non-login shells.'
steve@steve-Satellite-C655D:~$ rip
No command 'rip' found, but there are 17 similar ones
rip: command not found
steve@steve-Satellite-C655D:~$ echo $PATH
/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
steve@steve-Satellite-C655D:~$ 

This is what happened.

**Comment by NapoleonWils0n** [comment] 2016-06-15 20:04
Hi steve55792, you seem to have a typo in your bashrc

there is no command called rip, 
but if you type the word rip and press tab you get the list of all the commands
was just to check if the scripts where being sourced in your bash path

do you want to post your .bashrc and ill see what the typo is

**Comment by steve55792** [comment] 2016-06-15 20:07
if [ -d "$HOME/git/kodi-playercorefactory/bash-scripts" ] ; then
        PATH="$HOME/git/kodi-playercorefactory/bash-scripts:$PATH"
fi# ~/.bashrc: executed by bash(1) for non-login shells.
# see /usr/share/doc/bash/examples/startup-files (in the package bash-doc)
# for examples

# If not running interactively, don't do anything
case $- in
    *i*) ;;
      *) return;;
esac

# don't put duplicate lines or lines starting with space in the history.
# See bash(1) for more options
HISTCONTROL=ignoreboth

# append to the history file, don't overwrite it
shopt -s histappend

# for setting history length see HISTSIZE and HISTFILESIZE in bash(1)
HISTSIZE=1000
HISTFILESIZE=2000

# check the window size after each command and, if necessary,
# update the values of LINES and COLUMNS.
shopt -s checkwinsize

# If set, the pattern "**" used in a pathname expansion context will
# match all files and zero or more directories and subdirectories.
#shopt -s globstar

# make less more friendly for non-text input files, see lesspipe(1)
[ -x /usr/bin/lesspipe ] && eval "$(SHELL=/bin/sh lesspipe)"

# set variable identifying the chroot you work in (used in the prompt below)
if [ -z "${debian_chroot:-}" ] && [ -r /etc/debian_chroot ]; then
    debian_chroot=$(cat /etc/debian_chroot)
fi

# set a fancy prompt (non-color, unless we know we "want" color)
case "$TERM" in
    xterm-color|*-256color) color_prompt=yes;;
esac

# uncomment for a colored prompt, if the terminal has the capability; turned
# off by default to not distract the user: the focus in a terminal window
# should be on the output of commands, not on the prompt
#force_color_prompt=yes

if [ -n "$force_color_prompt" ]; then
    if [ -x /usr/bin/tput ] && tput setaf 1 >&/dev/null; then
	# We have color support; assume it's compliant with Ecma-48
	# (ISO/IEC-6429). (Lack of such support is extremely rare, and such
	# a case would tend to support setf rather than setaf.)
	color_prompt=yes
    else
	color_prompt=
    fi
fi

if [ "$color_prompt" = yes ]; then
    PS1='${debian_chroot:+($debian_chroot)}\[\033[01;32m\]\u@\h\[\033[00m\]:\[\033[01;34m\]\w\[\033[00m\]\$ '
else
    PS1='${debian_chroot:+($debian_chroot)}\u@\h:\w\$ '
fi
unset color_prompt force_color_prompt

# If this is an xterm set the title to user@host:dir
case "$TERM" in
xterm*|rxvt*)
    PS1="\[\e]0;${debian_chroot:+($debian_chroot)}\u@\h: \w\a\]$PS1"
    ;;
*)
    ;;
esac

# enable color support of ls and also add handy aliases
if [ -x /usr/bin/dircolors ]; then
    test -r ~/.dircolors && eval "$(dircolors -b ~/.dircolors)" || eval "$(dircolors -b)"
    alias ls='ls --color=auto'
    #alias dir='dir --color=auto'
    #alias vdir='vdir --color=auto'

    alias grep='grep --color=auto'
    alias fgrep='fgrep --color=auto'
    alias egrep='egrep --color=auto'
fi

# colored GCC warnings and errors
#export GCC_COLORS='error=01;31:warning=01;35:note=01;36:caret=01;32:locus=01:quote=01'

# some more ls aliases
alias ll='ls -alF'
alias la='ls -A'
alias l='ls -CF'

# Add an "alert" alias for long running commands.  Use like so:
#   sleep 10; alert
alias alert='notify-send --urgency=low -i "$([ $? = 0 ] && echo terminal || echo error)" "$(history|tail -n1|sed -e '\''s/^\s*[0-9]\+\s*//;s/[;&|]\s*alert$//'\'')"'

# Alias definitions.
# You may want to put all your additions into a separate file like
# ~/.bash_aliases, instead of adding them here directly.
# See /usr/share/doc/bash-doc/examples in the bash-doc package.

if [ -f ~/.bash_aliases ]; then
    . ~/.bash_aliases
fi

# enable programmable completion features (you don't need to enable
# this, if it's already enabled in /etc/bash.bashrc and /etc/profile
# sources /etc/bash.bashrc).
if ! shopt -oq posix; then
  if [ -f /usr/share/bash-completion/bash_completion ]; then
    . /usr/share/bash-completion/bash_completion
  elif [ -f /etc/bash_completion ]; then
    . /etc/bash_completion
  fi

fi

**Comment by steve55792** [comment] 2016-06-15 20:09
if [ -d "$HOME/git/kodi-playercorefactory/bash-scripts" ] ; then
        PATH="$HOME/git/kodi-playercorefactory/bash-scripts:$PATH"
fi# ~/.bashrc: executed by bash(1) for non-login shells.

# see /usr/share/doc/bash/examples/startup-files (in the package bash-doc)

# for examples

# If not running interactively, don't do anything

case $- in
    _i_) ;;
      *) return;;
esac

# don't put duplicate lines or lines starting with space in the history.

# See bash(1) for more options

HISTCONTROL=ignoreboth

# append to the history file, don't overwrite it

shopt -s histappend

# for setting history length see HISTSIZE and HISTFILESIZE in bash(1)

HISTSIZE=1000
HISTFILESIZE=2000

# check the window size after each command and, if necessary,

# update the values of LINES and COLUMNS.

shopt -s checkwinsize

# If set, the pattern "**" used in a pathname expansion context will

# match all files and zero or more directories and subdirectories.

#shopt -s globstar

# make less more friendly for non-text input files, see lesspipe(1)

[ -x /usr/bin/lesspipe ] && eval "$(SHELL=/bin/sh lesspipe)"

# set variable identifying the chroot you work in (used in the prompt below)

if [ -z "${debian_chroot:-}" ] && [ -r /etc/debian_chroot ]; then
    debian_chroot=$(cat /etc/debian_chroot)
fi

# set a fancy prompt (non-color, unless we know we "want" color)

case "$TERM" in
    xterm-color|*-256color) color_prompt=yes;;
esac

# uncomment for a colored prompt, if the terminal has the capability; turned

# off by default to not distract the user: the focus in a terminal window

# should be on the output of commands, not on the prompt

#force_color_prompt=yes

if [ -n "$force_color_prompt" ]; then
    if [ -x /usr/bin/tput ] && tput setaf 1 >&/dev/null; then
    # We have color support; assume it's compliant with Ecma-48
    # (ISO/IEC-6429). (Lack of such support is extremely rare, and such
    # a case would tend to support setf rather than setaf.)
    color_prompt=yes
    else
    color_prompt=
    fi
fi

if [ "$color_prompt" = yes ]; then
    PS1='${debian_chroot:+($debian_chroot)}[\033[01;32m]\u@\h[\033[00m]:[\033[01;34m]\w[\033[00m]\$ '
else
    PS1='${debian_chroot:+($debian_chroot)}\u@\h:\w\$ '
fi
unset color_prompt force_color_prompt

# If this is an xterm set the title to user@host:dir

case "$TERM" in
xterm_|rxvt_)
    PS1="[\e]0;${debian_chroot:+($debian_chroot)}\u@\h: \w\a]$PS1"
    ;;
*)
    ;;
esac

# enable color support of ls and also add handy aliases

if [ -x /usr/bin/dircolors ]; then
    test -r ~/.dircolors && eval "$(dircolors -b ~/.dircolors)" || eval "$(dircolors -b)"
    alias ls='ls --color=auto'
    #alias dir='dir --color=auto'
    #alias vdir='vdir --color=auto'

```
alias grep='grep --color=auto'
alias fgrep='fgrep --color=auto'
alias egrep='egrep --color=auto'
```

fi

# colored GCC warnings and errors

#export GCC_COLORS='error=01;31:warning=01;35:note=01;36:caret=01;32:locus=01:quote=01'

# some more ls aliases

alias ll='ls -alF'
alias la='ls -A'
alias l='ls -CF'

# Add an "alert" alias for long running commands.  Use like so:

# sleep 10; alert

alias alert='notify-send --urgency=low -i "$([ $? = 0 ] && echo terminal || echo error)" "$(history|tail -n1|sed -e '\''s/^\s_[0-9]+\s_//;s/[;&|]\s*alert$//'\'')"'

# Alias definitions.

# You may want to put all your additions into a separate file like

# ~/.bash_aliases, instead of adding them here directly.

# See /usr/share/doc/bash-doc/examples in the bash-doc package.

if [ -f ~/.bash_aliases ]; then
    . ~/.bash_aliases
fi

# enable programmable completion features (you don't need to enable

# this, if it's already enabled in /etc/bash.bashrc and /etc/profile

# sources /etc/bash.bashrc).

if ! shopt -oq posix; then
  if [ -f /usr/share/bash-completion/bash_completion ]; then
    . /usr/share/bash-completion/bash_completion
  elif [ -f /etc/bash_completion ]; then
    . /etc/bash_completion
  fi

fi

**Comment by steve55792** [comment] 2016-06-15 20:16
sorry, that how it turned out.

**Comment by NapoleonWils0n** [comment] 2016-06-15 20:31
Hi steve55792, no problem gave me a laugh
I see what the problem is 

You have pasted the code into another piece of code by mistake

Can you change the code at top of your ~/.bashrc
from this

```
if [ -d "$HOME/git/kodi-playercorefactory/bash-scripts" ] ; then
PATH="$HOME/git/kodi-playercorefactory/bash-scripts:$PATH"
fi# ~/.bashrc: executed by bash(1) for non-login shells.
```

remove the first 2 lines
and the word fi in front the # symbol
so it looks like this

```
# ~/.bashrc: executed by bash(1) for non-login shells.
```

Then paste the code below at the bottom of the ~/bashrc file

```
if [ -d "$HOME/git/kodi-playercorefactory/bash-scripts" ] ; then
        PATH="$HOME/git/kodi-playercorefactory/bash-scripts:$PATH"
fi
```

the top of your bashrc should look like this
https://gist.github.com/marioBonales/1637696

Then source your bashrc again, by running the command below in the terminal

```
source ~/.bashrc
```

And check your bash path for good measure, by running the command below in the terminal

```
echo $PATH
```

See if that solves the issue

**Comment by steve55792** [comment] 2016-06-15 21:15
I dont know if it helped or not but here is the outcome: bash: /home/steve/.bashrc: line 2: syntax error near unexpected token `('
bash: /home/steve/.bashrc: line 2:` ~/.bashrc: executed by bash(1) for non-login shells.'
/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin

**Comment by NapoleonWils0n** [comment] 2016-06-15 21:19
Hi steve55792
you still have a typo on line 2 

the first 3 lines should look like this

```
# ~/.bashrc: executed by bash(1) for non-login shells.
# see /usr/share/doc/bash/examples/startup-files (in the package bash-doc)
# for examples
```

make sure there is a # in front  ~/.bashrc: executed by bash(1) for non-login shells.

like this 

```
# ~/.bashrc: executed by bash(1) for non-login shells.
```

then try sourcing the bashrc again

```
source ~/.bashrc
```

**Comment by steve55792** [comment] 2016-06-15 21:31
now what happened:  bash: /home/steve/.bashrc: line 122: syntax error: unexpected end of file
here is the bashrc again:

# ~/.bashrc: executed by bash(1) for non-login shells.

# see /usr/share/doc/bash/examples/startup-files (in the package bash-doc)

# for examples

# If not running interactively, don't do anything

case $- in
    _i_) ;;
      *) return;;
esac

# don't put duplicate lines or lines starting with space in the history.

# See bash(1) for more options

HISTCONTROL=ignoreboth

# append to the history file, don't overwrite it

shopt -s histappend

# for setting history length see HISTSIZE and HISTFILESIZE in bash(1)

HISTSIZE=1000
HISTFILESIZE=2000

# check the window size after each command and, if necessary,

# update the values of LINES and COLUMNS.

shopt -s checkwinsize

# If set, the pattern "**" used in a pathname expansion context will

# match all files and zero or more directories and subdirectories.

#shopt -s globstar

# make less more friendly for non-text input files, see lesspipe(1)

[ -x /usr/bin/lesspipe ] && eval "$(SHELL=/bin/sh lesspipe)"

# set variable identifying the chroot you work in (used in the prompt below)

if [ -z "${debian_chroot:-}" ] && [ -r /etc/debian_chroot ]; then
    debian_chroot=$(cat /etc/debian_chroot)
fi

# set a fancy prompt (non-color, unless we know we "want" color)

case "$TERM" in
    xterm-color|*-256color) color_prompt=yes;;
esac

# uncomment for a colored prompt, if the terminal has the capability; turned

# off by default to not distract the user: the focus in a terminal window

# should be on the output of commands, not on the prompt

#force_color_prompt=yes

if [ -n "$force_color_prompt" ]; then
    if [ -x /usr/bin/tput ] && tput setaf 1 >&/dev/null; then
    # We have color support; assume it's compliant with Ecma-48
    # (ISO/IEC-6429). (Lack of such support is extremely rare, and such
    # a case would tend to support setf rather than setaf.)
    color_prompt=yes
    else
    color_prompt=
    fi
fi

if [ "$color_prompt" = yes ]; then
    PS1='${debian_chroot:+($debian_chroot)}[\033[01;32m]\u@\h[\033[00m]:[\033[01;34m]\w[\033[00m]\$ '
else
    PS1='${debian_chroot:+($debian_chroot)}\u@\h:\w\$ '
fi
unset color_prompt force_color_prompt

# If this is an xterm set the title to user@host:dir

case "$TERM" in
xterm_|rxvt_)
    PS1="[\e]0;${debian_chroot:+($debian_chroot)}\u@\h: \w\a]$PS1"
    ;;
*)
    ;;
esac

# enable color support of ls and also add handy aliases

if [ -x /usr/bin/dircolors ]; then
    test -r ~/.dircolors && eval "$(dircolors -b ~/.dircolors)" || eval "$(dircolors -b)"
    alias ls='ls --color=auto'
    #alias dir='dir --color=auto'
    #alias vdir='vdir --color=auto'

```
alias grep='grep --color=auto'
alias fgrep='fgrep --color=auto'
alias egrep='egrep --color=auto'
```

fi

# colored GCC warnings and errors

#export GCC_COLORS='error=01;31:warning=01;35:note=01;36:caret=01;32:locus=01:quote=01'

# some more ls aliases

alias ll='ls -alF'
alias la='ls -A'
alias l='ls -CF'

# Add an "alert" alias for long running commands.  Use like so:

# sleep 10; alert

alias alert='notify-send --urgency=low -i "$([ $? = 0 ] && echo terminal || echo error)" "$(history|tail -n1|sed -e '\''s/^\s_[0-9]+\s_//;s/[;&|]\s*alert$//'\'')"'

# Alias definitions.

# You may want to put all your additions into a separate file like

# ~/.bash_aliases, instead of adding them here directly.

# See /usr/share/doc/bash-doc/examples in the bash-doc package.

if [ -f ~/.bash_aliases ]; then
    . ~/.bash_aliases
fi

# enable programmable completion features (you don't need to enable

# this, if it's already enabled in /etc/bash.bashrc and /etc/profile

# sources /etc/bash.bashrc).

if ! shopt -oq posix; then
  if [ -f /usr/share/bash-completion/bash_completion ]; then
    . /usr/share/bash-completion/bash_completion
  elif [ -f /etc/bash_completion ]; then
    . /etc/bash_completion
  fi

if [ -d "$HOME/git/kodi-playercorefactory/bash-scripts" ] ; then
        PATH="$HOME/git/kodi-playercorefactory/bash-scripts:$PATH"
fi

**Comment by NapoleonWils0n** [comment] 2016-06-15 21:49
Hi steve55792, 
best thing is to start with a fresh bashrc and the add the code again

There is a default bashrc that comes with all linux operating system like ubuntu,
and we are going use that to restore your bashrc file and then add the path to the kodi scripts again

1 - open the file manager and press control and h on the keyboard to show hidden files

2 - move the .bashrc file to your desktop, 
then select the file on the desktop and rename it to bashrc-old ( remove the dot prefix, eg it should be name bashrc-old and not .bashrc-old )

3 - open the terminal, and paste in the following command 
This will create a new ~/.bashrc in your home folder with all the default settings

```
cp /etc/skel/.bashrc ~/.bashrc
```

4 - right click on the new ~/.bashrc and select open with gedit
then paste the code at the below at the bottom of the ~/.bashrc file and then save the file

```
if [ -d "$HOME/git/kodi-playercorefactory/bash-scripts" ] ; then
PATH="$HOME/git/kodi-playercorefactory/bash-scripts:$PATH"
fi
```

5 - Source your bashrc

```
source ~/.bashrc
```

6 - Check your bash path

```
echo $PATH
```

**Comment by steve55792** [comment] 2016-06-15 23:45
after pasting is there supposed to be 2 fi at the bottom or one?
But anyways no error after sources the bashrc and checking bash path turned out:
/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin

**Comment by NapoleonWils0n** [comment] 2016-06-16 00:07
Hi steve55792
Just made a new youtube tutorial on how to set everything up on ubuntu

That will show you what the ~/.bashrc file is supposed to look like

Ubuntu 16.04 LTS install tools and bash scripts in 5 mins - kodi recording videos 102

https://www.youtube.com/watch?v=3pC8kMbAhKw

**Comment by steve55792** [comment] 2016-06-16 00:12
Thank you. Going thru all that i tried using the script and i clicked on y and it only said dvd default player. Did the script got deleted some how? For shits and giggles I dont have a tab button on my laptop. Its a toshiba

**Comment by NapoleonWils0n** [comment] 2016-06-16 00:21
Hi steve55792 
Close Kodi and then re open Kodi and check again
Kodi wont pick up the playercorefactory.xml file if kodi is running

Make sure the playercorefactory.xml is in the kodi userdata folder

if in doubt watch the video again

**Comment by steve55792** [comment] 2016-06-16 00:24
im sorry this is before the video 102 it happened. i just started watching the video.

**Comment by steve55792** [comment] 2016-06-16 02:09
got it back running but its not saving to the video to desktop

**Comment by steve55792** [comment] 2016-06-16 11:30
dummy me I used the windows playercorefactory.xml instead of linux one, but its working now where its saving on the desktop. but its time to learn how to rip-record-batch in the linux setup.

**Comment by NapoleonWils0n** [comment] 2016-06-16 12:51
Hi steve55792
glad you managed to get it working 

ill close this issue

**Closed as completed by NapoleonWils0n** 2016-06-16 12:51 UTC
